# Site Settings
locale: "en-US"
title: "Elio Verhoef"
title_separator: "-"
name: &name "Elio Verhoef"
description: &description "Innovator in AI and Programming"
url: https://elioverhoef.github.io
baseurl: ""
repository: "elioverhoef.github.io"
teaser:
logo: "/images/logo.png"
masthead_title: "Elio Verhoef"
breadcrumbs: false
words_per_minute: 200

# Site Author
author:
  name: "Elio Verhoef"
  avatar: "/images/profile.png"
  bio: "Innovator in AI, Programming, and Longevity"
  location: "The Netherlands"
  email:
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/c/ElioVerhoef"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elioverhoef"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/elio-verhoef-699462291"

# Site Footer
footer:
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/c/ElioVerhoef"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elioverhoef"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/elio-verhoef-699462291"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
